version: 2
updates:
  - package-ecosystem: "nuget"
    directory: "/WorldClockWpf"
    schedule:
      interval: "weekly"

  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "weekly"
